name:                autodiff
version:             0.1.0.0
github:              "githubuser/autodiff"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/autodiff#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- template-haskell
- QuickCheck
- dependent-map
- dependent-sum-template
- some
- hmatrix
- constraints
- constraints-extras
- deepseq
- th-compat
- semirings
- containers

default-extensions:
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- PolyKinds
- StandaloneDeriving
- DeriveFunctor
- DeriveGeneric
- DerivingVia
- UndecidableInstances
- ScopedTypeVariables
- DataKinds
- KindSignatures
- StandaloneKindSignatures
- TypeApplications
- GADTs
- QuantifiedConstraints
- RankNTypes
- TemplateHaskell
- TypeOperators
- TypeFamilies
- FlexibleContexts
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  autodiff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprint-potential-instances
    - -dth-dec-file
    dependencies:
    - autodiff
    - dependent-sum
    - backprop
    - microlens-th
    - hmatrix-backprop

tests:
  autodiff-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ddump-splices
    - -ddump-to-file
    dependencies:
    - autodiff

benchmarks:
  algebraic-benches:
    main:                Main.hs
    source-dirs:         bench
    dependencies:
      - autodiff
      - criterion
      - deepseq
      - backprop
      - hmatrix-backprop
      - microlens
      - microlens-th
      - dependent-sum
      - directory 
      - vector 
      - time
      - mwc-random
      - tuple
      - ad
    ghc-options:
      - -O2
      - -rtsopts
      - -ddump-splices
      - -ddump-to-file
        #- -with-rtsopts=-N
